apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  containers:
    - name: elasticsearch-container
      image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
      env:
        - name: discovery.type
          value: single-node
      
      ports:
        - containerPort: 9200
          protocol: TCP