version: "3"
services:
  db:
    container_name: tc_database
    build: ./banco/
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ROOTPASS
      MYSQL_DATABASE: TechChallenge
      
    networks:
      - tc_network
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  app:
    container_name: tc_api
    build: ./backend/
    ports:
      - "80:80"
    networks:
      - tc_network
    depends_on:
      - db
    environment:
      MYSQL_ROOT_PASSWORD: ROOTPASS
      MYSQL_DATABASE: TechChallenge
      MYSQL_HOST: tc_database
      MYSQL_USER: root
      MYSQL_PASS: ROOTPASS
      MYSQL_PORT: 3306
  
  # frontend:
  #   container_name: restaurante_mobile
  #   build: ./restaurante-mobile/
  #   ports:
  #     - 19000:19000
  #     - 19001:19001
  #     - 19002:19002
  #     - 8081:8081
      
  #   environment:
  #     - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
  #     - CHOKIDAR_USEPOLLING=true    

networks:
  tc_network:
    name: tc_network
    