apiVersion: v1
kind: Pod
metadata:
 name: pod-backend
 labels:
   app: pod-backend
spec:
 containers:
 - name: tcapi
   image: soluo-tc-app:latest
   ports:
   - containerPort: 80
     protocol: TCP
   resources:
     limits:
       cpu: "0.5"
       memory: "512Mi"
     requests:
       cpu: "0.2"
       memory: "256Mi"
   volumeMounts:
   - name: tc-volume
     mountPath: /code
 volumes:
 - name: tc-volume
   emptyDir: {}