version: "3.8"

services:
  expo_app:
    container_name: restaurante_app
    build: .
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 8081:8081
      
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - CHOKIDAR_USEPOLLING=true