apiVersion: batch/v1
kind: CronJob
metadata:
  name: fiap-cronjob
spec:
  schedule: "1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
                - /bin/sh
                - -c
                - date; echo Ola Fiap curso de Kubernetes
          restartPolicy: OnFailure