apiVersion: batch/v1
kind: Job
metadata:
  name: fiap-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: hello
        image: busybox:1.28
        command:
            - /bin/sh
            - -c
            - date; echo Ola Fiap curso de Kubernetes
      restartPolicy: Never