apiVersion: v1
kind: Service
metadata:
  name: svc-backend
spec:
  type: NodePort
  selector:
    app: pod-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000